CREATE ROLE fa WITH PASSWORD 'fa4data';
ALTER ROLE fa WITH LOGIN;
ALTER ROLE fa WITH SUPERUSER;

CREATE DATABASE fullaux;
ALTER DATABASE fullaux owner to fa;

GRANT ALL PRIVILEGES ON SCHEMA public TO fa;

