apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fa-postgres-rev
  name: fa-postgres-pv-claim-rev
spec:
  storageClassName: hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi